### ISSUE TITLE
Feature Request: Connect to TireLinc

### ISSUE THREAD

**Issue by k3vmcd** [bkbilly/tpms_ble#3]
Request to read TireLinc system. Manufacturer ID is 0x05C7 registered by 'Lippert Components, INC'.

**Comment by bkbilly** [comment]
You could try editing the manifest.json file to add the **manufacturer_id** with value **1479**.
Could you also tell me what the Service UUID is for your device?

**Comment by k3vmcd** [comment]
I tried a few things to discover the TireLinc. None of these worked.

1. Setting `"manufacturer_id": 1479` in manifest.json
2. Additionally setting `TPMS_MANUFACTURER = 1479` in tpms_parser/parser.py combined with above
3. Swapping `"manufacturer_id": 256` to `"local_name": "TireLinc*"` in manifest.json with both default and modified tpms_parser/parser.py. Modifications to tpms_parser/parser.py were:
- Switching just the manufacturer id: `TPMS_MANUFACTURER = 1479`
- Trying to comment out the TPMS_MANUFACTURER section and setting mfr_data from the discovered data
```
        # if TPMS_MANUFACTURER not in manufacturer_data:
        #     return None

        # mfr_data = manufacturer_data[TPMS_MANUFACTURER]
        mfr_data = service_info.manufacturer_data
```

**Comment by k3vmcd** [comment]
The Service UUID is 00000000-00b7-4807-beee-e0b0879cf3dd

**Comment by bkbilly** [comment]
The way the data are decoded might be different with the ones I use. 
Could you send me all the data that your TPMS is sending?

**Comment by k3vmcd** [comment]
Here is what I see so far. This should be connected to the repeater. It looks like the custom service UUID may have the four slots for the four tires. The tires have internal sensors. 

When I try to read the data or click notify it gives different data. 

I haven't been able to get it to bond, it errors with an incorrect PIN.

I realize it's not much. I've had major issues with getting the manufacturer's app to work, which is one of the reasons I want to connect this with Home Assistant other than being able to track the history better. 

I'll keep trying to gather better data. 


![Screenshot_20240422-103458.png](https://github.com/bkbilly/tpms_ble/assets/5653317/18937518-1f74-4559-badb-abdb945a323c)

![Screenshot_20240422-103640.png](https://github.com/bkbilly/tpms_ble/assets/5653317/0b9a4651-063f-459d-943d-6de2f0b919ae)

![Screenshot_20240422-103734.png](https://github.com/bkbilly/tpms_ble/assets/5653317/2567ad81-6ffc-4225-805d-6f745a13f950)

**Comment by k3vmcd** [comment]
Also, at one point I may have gotten it to connect a different way and it appeared to spawn 4 separate tabs that may have been the individual tire data. Unfortunately it disconnects very quickly and I haven't been able to get nrRF Connect to do that again.

**Comment by k3vmcd** [comment]
Also, at one point I may have gotten it to connect a different way and it appeared to spawn 4 separate tabs that may have been the individual tire data. Unfortunately it disconnects very quickly and I haven't been able to get nRF Connect to do that again.

**Comment by bkbilly** [comment]
It seems that TireLinc is using a central device to get information from the sensors on your tires.
Unfortunately I can't support this central device.
I would recommend getting the data directly from the tire sensors and remove the central device.

If they are similar to mine, they send their passive data every 5 minutes, so you could capture it with nRF Connect and even clone it for testing it out.
These sensors don't support connect because all their data exist under their manufacturer data.
If you capture them, send me a screenshot to check if I can make it compatible with my integration.

**Comment by k3vmcd** [comment]
I'm pretty sure the central device is just repeating the signal (this is a unit on a fifth wheel trailer / RV). I'll disconnect the central repeater and see what data I can pull directly off the tire sensors as you suggest.

**Comment by k3vmcd** [comment]
After further research, I found that the individual tire sensors report using 443 MHz instead of Bluetooth. The central hub is what gathers the 443 MHz signals and reports them over Bluetooth. Reference spec doc is here: https://lci-support-doc.s3.amazonaws.com/specification_sheets/ccd-0007698.pdf

Exploring more with nRF Connect, I was able to gather the following log by subscribing to notifications on the custom characteristic.

At the time of this log, the PSI and temperature readings in order of what I believe are the same order the TPMS would report them:

1. Front Left (not reporting on TPMS device, but should be same/close to others)
2. Rear Left 121 PSI / 68 F
3. Front Right 121 PSI / 68 F
4. Rear Right 122 PSI / 68 F

```
nRF Connect, 2024-04-30
TireLinc (F4:12:FA:45:F4:5A)
V	16:09:36.652	Connecting to F4:12:FA:45:F4:5A...
D	16:09:36.652	gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE, preferred PHY = LE 1M)
D	16:09:36.894	[Callback] Connection state changed with status: 0 and new state: CONNECTED (2)
I	16:09:36.894	Connected to F4:12:FA:45:F4:5A
V	16:09:36.970	Discovering services...
D	16:09:36.970	gatt.discoverServices()
D	16:09:37.215	[Broadcast] Action received: android.bluetooth.device.action.ACL_CONNECTED
I	16:09:37.645	Connection parameters updated (interval: 7.5ms, latency: 0, timeout: 5000ms)
D	16:09:37.954	[Callback] Services discovered with status: 0
I	16:09:37.954	Services discovered
V	16:09:37.959	Generic Attribute (0x1801)
- Service Changed [I] (0x2A05)
   Client Characteristic Configuration (0x2902)
Generic Access (0x1800)
- Device Name [R] (0x2A00)
- Appearance [R] (0x2A01)
- Central Address Resolution [R] (0x2AA6)
Unknown Service (00000000-00b7-4807-beee-e0b0879cf3dd)
- Unknown Characteristic [R W] (00000001-00b7-4807-beee-e0b0879cf3dd)
   Characteristic User Description (0x2901)
- Unknown Characteristic [N R] (00000002-00b7-4807-beee-e0b0879cf3dd)
   Characteristic User Description (0x2901)
   Client Characteristic Configuration (0x2902)
- Unknown Characteristic [N R] (00000003-00b7-4807-beee-e0b0879cf3dd)
   Characteristic User Description (0x2901)
   Client Characteristic Configuration (0x2902)
- Unknown Characteristic [R] (00000004-00b7-4807-beee-e0b0879cf3dd)
   Characteristic User Description (0x2901)
Device Information (0x180A)
- Firmware Revision String [R] (0x2A26)
- Hardware Revision String [R] (0x2A27)
D	16:09:37.959	gatt.setCharacteristicNotification(00002a05-0000-1000-8000-00805f9b34fb, true)
D	16:09:37.960	gatt.setCharacteristicNotification(00000002-00b7-4807-beee-e0b0879cf3dd, true)
D	16:09:37.961	gatt.setCharacteristicNotification(00000003-00b7-4807-beee-e0b0879cf3dd, true)
I	16:09:38.055	Connection parameters updated (interval: 30.0ms, latency: 0, timeout: 4000ms)
V	16:09:41.571	Enabling notifications for 00000002-00b7-4807-beee-e0b0879cf3dd
D	16:09:41.571	gatt.setCharacteristicNotification(00000002-00b7-4807-beee-e0b0879cf3dd, true)
D	16:09:41.577	gatt.writeDescriptor(00002902-0000-1000-8000-00805f9b34fb, value=0x0100)
I	16:09:41.625	Data written to descr. 00002902-0000-1000-8000-00805f9b34fb, value: (0x) 01-00
A	16:09:41.625	"Notifications enabled" sent
V	16:09:41.628	Notifications enabled for 00000002-00b7-4807-beee-e0b0879cf3dd
I	16:09:42.620	Notification received from 00000002-00b7-4807-beee-e0b0879cf3dd, value: (0x) 04-02-04-00
A	16:09:42.620	"(0x) 04-02-04-00" received
I	16:09:42.647	Notification received from 00000002-00b7-4807-beee-e0b0879cf3dd, value: (0x) 01-08-02-03-00-00-00-00-00-00
A	16:09:42.647	"(0x) 01-08-02-03-00-00-00-00-00-00" received
I	16:09:42.652	Notification received from 00000002-00b7-4807-beee-e0b0879cf3dd, value: (0x) 02-0E-B3-0B-02-00-01-78-00-93-00-96-00-3C-00-00
A	16:09:42.652	"(0x) 02-0E-B3-0B-02-00-01-78-00-93-00-96-00-3C-00-00" received
I	16:09:42.652	Notification received from 00000002-00b7-4807-beee-e0b0879cf3dd, value: (0x) 02-0E-88-46-02-00-09-78-00-93-00-96-00-3C-00-01
A	16:09:42.652	"(0x) 02-0E-88-46-02-00-09-78-00-93-00-96-00-3C-00-01" received
I	16:09:42.676	Notification received from 00000002-00b7-4807-beee-e0b0879cf3dd, value: (0x) 02-0E-FF-47-02-00-11-78-00-93-00-96-00-3C-00-02
A	16:09:42.676	"(0x) 02-0E-FF-47-02-00-11-78-00-93-00-96-00-3C-00-02" received
I	16:09:42.676	Notification received from 00000002-00b7-4807-beee-e0b0879cf3dd, value: (0x) 02-0E-61-3A-02-00-19-78-00-93-00-96-00-3C-00-03
A	16:09:42.676	"(0x) 02-0E-61-3A-02-00-19-78-00-93-00-96-00-3C-00-03" received
I	16:09:42.860	Notification received from 00000002-00b7-4807-beee-e0b0879cf3dd, value: (0x) 00-0E-B3-0B-02-00-C1-45-00-79-00-14-00-DD-40-80
A	16:09:42.860	"(0x) 00-0E-B3-0B-02-00-C1-45-00-79-00-14-00-DD-40-80" received
I	16:09:42.861	Notification received from 00000002-00b7-4807-beee-e0b0879cf3dd, value: (0x) 00-0E-88-46-02-00-C1-44-00-79-00-14-00-E1-00-C2
A	16:09:42.861	"(0x) 00-0E-88-46-02-00-C1-44-00-79-00-14-00-E1-00-C2" received
I	16:09:42.888	Notification received from 00000002-00b7-4807-beee-e0b0879cf3dd, value: (0x) 00-0E-FF-47-02-00-B1-44-00-79-00-14-00-E8-00-C9
A	16:09:42.888	"(0x) 00-0E-FF-47-02-00-B1-44-00-79-00-14-00-E8-00-C9" received
I	16:09:42.888	Notification received from 00000002-00b7-4807-beee-e0b0879cf3dd, value: (0x) 00-0E-61-3A-02-00-C1-44-00-7A-00-14-00-E2-00-CC
A	16:09:42.888	"(0x) 00-0E-61-3A-02-00-C1-44-00-7A-00-14-00-E2-00-CC" received
D	16:09:46.958	[Callback] Connection state changed with status: 19 and new state: DISCONNECTED (0)
W	16:09:46.958	Connection terminated by peer (status 19)
I	16:09:46.958	Disconnected
D	16:09:47.014	[Broadcast] Action received: android.bluetooth.device.action.ACL_DISCONNECTED
```

[Log 2024-04-30 16_09_50.txt](https://github.com/bkbilly/tpms_ble/files/15171252/Log.2024-04-30.16_09_50.txt)

**Comment by k3vmcd** [comment]
I think I may have found the relevant bytes. I'm not sure what the rest of them are used for, but these seem to be the and the configured alert thresholds and the temperature and pressure readings.

Values below are arranged in row-pairs with:
1. raw Hex value
2. values converted to decimal

First it reports the configured alert thresholds. I have these thresholds set for all four tires:
Minimum Pressure: 120 PSI
Maximum Pressure: 147 PSI
Maximum Temperature: 150 F
Maximum Temp Change: 60 F

02-0E-B3-0B-02-00-01-**78**-00-**93**-00-**96**-00-**3C**-00-00
2-14-179-11-2-0-1-**120**-0-**147**-0-**150**-0-**60**-0-0

02-0E-88-46-02-00-09-**78**-00-**93**-00-**96**-00-**3C**-00-01
2-14-136-70-2-0-9-**120**-0-**147**-0-**150**-0-**60**-0-1

02-0E-FF-47-02-00-11-**78**-00-**93**-00-**96**-00-**3C**-00-02
2-14-255-71-2-0-17-**120**-0-**147**-0-**150**-0-**60**-0-2

02-0E-61-3A-02-00-19-**78**-00-**93**-00-**96**-00-**3C**-00-03
2-14-97-58-2-0-25-**120**-0-**147**-0-**150**-0-**60**-0-3

Next it reports the individual tire readings

00-0E-B3-0B-02-00-C1-**45**-00-**79**-00-14-00-DD-40-80
0-14-179-11-2-0-193-**69**-0-**121**-0-20-0-221-64-128

00-0E-88-46-02-00-C1-**44**-00-**79**-00-14-00-E1-00-C2
0-14-136-70-2-0-193-**68**-0-**121**-0-20-0-225-0-194

00-0E-FF-47-02-00-B1-**44**-00-**79**-00-14-00-E8-00-C9
0-14-255-71-2-0-177-**68**-0-**121**-0-20-0-232-0-201

00-0E-61-3A-02-00-C1-**44**-00-**7A**-00-14-00-E2-00-CC
0-14-97-58-2-0-193-**68**-0-**122**-0-20-0-226-0-204

**Comment by bkbilly** [comment]
This info you gathered is very helpful for creating a new integration.
There isn't any official Bluetooth integration for Home Assistant that use notifications, except some custom integrations.

I've created one for Medisana Blood Pressure devices that should help you if you want to create it.
You can find the file for collecting and parsing the data here: https://github.com/bkbilly/medisanabp_ble/blob/main/custom_components/medisanabp_ble/medisana_bp/parser.py

There are a lot of places that need changing, but here are a few tips for the parser that needs to be changed:
 * Replace the `CHARACTERISTIC_BLOOD_PRESSURE` variable with this: 00000002-00b7-4807-beee-e0b0879cf3dd
 * Edit the `notification_handler` to parse the data from your sensor 
 * You might want to remove the `asyncio.wait_for(self._event.wait(), 15)` because it will only read one of the sensors. On your application you want to read all the notifications.

I am not sure how these values could be parsed, but from my understanding you only need the bytes that are size of 16. 
These are HEX values that need to be converted to Decimal.
They seem to be split into two categories because they send 8 of them.
The 2nd until 5th byte seems to be the identification of the sensor, eg: `0E-B3-0B-02`.
```
02-0E-B3-0B-02-00-01-78-00-93-00-96-00-3C-00-00
02-0E-88-46-02-00-09-78-00-93-00-96-00-3C-00-01
02-0E-FF-47-02-00-11-78-00-93-00-96-00-3C-00-02
02-0E-61-3A-02-00-19-78-00-93-00-96-00-3C-00-03

00-0E-B3-0B-02-00-C1-45-00-79-00-14-00-DD-40-80
00-0E-88-46-02-00-C1-44-00-79-00-14-00-E1-00-C2
00-0E-FF-47-02-00-B1-44-00-79-00-14-00-E8-00-C9
00-0E-61-3A-02-00-C1-44-00-7A-00-14-00-E2-00-CC
```

From my understanding the ones starting with `02-...` are for the PSI and the ones starting with `00-...` are for the temperature. I believe the only bytes you need are the 7th and 8th byte for both of these categories.
Here are some of my calculations:
```
01-78  120.01
09-78  120.09
11-78  120.17
19-78  120.25

C1-45  69.193
C1-44  68.193
B1-44  68.177
C1-44  68.193
```

I am not sure if any of the above I mentioned is correct, but I think it's a first starting point.

**Comment by k3vmcd** [comment]
@bkbilly Well that was unbelievably difficult. Much appreciated for your help though, I couldn't have done it without your example. I finally got it to parse the multiple tires without errors, although I'm certain this code can be cleaned up to be more efficient. https://github.com/k3vmcd/ha-tirelinc

**Comment by bkbilly** [comment]
You're welcome! I'm glad my example helped you create this integration. It can definitely be tricky having to deal with active BLE sensors, so well done!
